# 공통 backend 설정
x-backend-common: &backend-common
  build:
    context: .
    dockerfile: Dockerfile
    args:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_VERSION: ${PROJECT_VERSION}
  image: ${PROJECT_NAME}:local-slim
  env_file:
    - .env.docker
  expose:
    - "8080"
  depends_on:
    - db
  networks:
    - otboo-network

# service
services:
  nginx:
    image: nginx:alpine
    container_name: otboo-nginx
    ports:
      - "3000:80"
    env_file:
      - .env.docker
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./src/main/resources/static:/usr/share/nginx/html:ro
    depends_on:
      - backend1
    networks:
      - otboo-network

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: otboo-db
    env_file:
      - .env.docker
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - otboo-postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - otboo-network

  backend1:
    <<: *backend-common
    container_name: otboo-backend-1

volumes:
  otboo-postgres-data:

networks:
  otboo-network:
    driver: bridge