upstream backend {
    ip_hash;
    keepalive 32;
    keepalive_requests 100;
    keepalive_timeout 60s;
    server 10.0.13.225:8080 max_fails=3 fail_timeout=30s;
}

server {
    listen 80;
    server_name localhost; # 서버 이름 > 도메인

    resolver 169.254.169.253 valid=10s;  # ECS VPC DNS

    # / 접속 시
    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri $uri/ /index.html;
    }

    # /api/ 접속 시
    location /api/ {
        proxy_pass http://backend;

        # 프록시 헤더 설정
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;                     # 실제 클라이언트 IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 프록시 체인
        proxy_set_header X-Forwarded-Port $server_port;              # 클라이언트가 사용한 포트 정보를 전달
        proxy_set_header X-Forwarded-Proto $scheme;                  # http or https
        proxy_set_header Authorization $http_authorization;          # 요청을 프록시할 때 Authorization 헤더를 전달

        # 타임아웃 설정
        proxy_connect_timeout 5s;  # 백엔드 연결 타임아웃
        proxy_send_timeout 60s;    # 요청 전송 타임아웃
        proxy_read_timeout 600s;   # 응답 읽기 타임아웃
        proxy_buffering off;       # SSE 버퍼링 방지
    }

    location ~ ^/(oauth2|login)/ {
        proxy_pass http://backend;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
        proxy_read_timeout 600s;
        proxy_buffering off;
    }

    # 웹소켓 및 SSE 프록시 (ex: /ws/ 또는 /api/sse)
    location /ws/ {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # 상태 페이지 (선택)
    location /nginx_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
    }

    location /health {
      return 200 'OK';
      add_header Content-Type text/plain;
    }

}